DjangoRegistroWeb/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('RegistroAppDocente.urls')),
]

RegistroAppDocente/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from django.conf import settings

#Ejemplo
#path('',index,name='IND'),
#path('galeria/',galeria,name='GALE'),
#path('quienes/',quienes,name='QUIEN'),
#path('formulario/',formulario,name='FORMU'),

urlpatterns = [
    path('',login,name='LOG'),
    path('dashboard/',index,name='IND'),
    path('asistencia/',asistencia,name='ASIS'),
    path('listaalumnos/',listaalumnos,name='LALU'),
    path('anotaciones/',anotaciones,name='ANOT'),
    path('comunicados/',comunicado,name='COM'),
    path('listacursos/',listacursos,name='LCUR'),
    path('modificarnotas/<int:curso_id>/', modificarnotas, name='MODN'),
    path('situacionalumnos/',situacionalumnos,name  ='SISA'),
    path('reprobar_alumno/<int:alumno_id>/',reprobar_alumno, name='reprobar_alumno'),
    path('notas/',notas,name='NON'),
    path('listaasistencia/',listaasistencia,name='LASIS'),
    path('historialcomunicados/', historialcomunicados, name="HSC"),
    path('historialanotaciones/', historialanotaciones, name="HAN"),
    path('Perfil/',perfilprofesor,name='PF'),
    path('api/periodosemestral/', PeriodoSemestralListCreateAPIView().as_view(), name='producto-list-create'),
    path('api/periodosemestral/<int:pk>/', PeriodoSemestralRetrieveUpdateDestroyAPIView.as_view(), name='producto-update'),
    path('api/cursos/', CursoListCreateAPIView.as_view(), name='contacto-list-create'),
    path('api/cursos/<int:pk>/', CursoRetrieveUpdateDestroyAPIView.as_view(), name='contacto-retrieve-update-destroy'),
    path('api/materias/', MateriaListCreateAPIView.as_view(), name='marcas-list-create'),
    path('api/materias/<int:pk>/', MateriaRetrieveUpdateDestroyAPIView.as_view(), name='marcas-retrieve-update-destroy'),
    path('api/alumnos/', AlumnoListCreateAPIView().as_view(), name='modelo-list-create'),
    path('api/alumnos/<int:pk>/', AlumnoRetrieveUpdateDestroyAPIView.as_view(), name='modelo-retrieve-update-destroy'),
    path('api/profesor/', ProfesorListCreateAPIView().as_view(), name='modelo-list-create'),
    path('api/profesor/<int:pk>/', ProfesorRetrieveUpdateDestroyAPIView.as_view(), name='modelo-retrieve-update-destroy'),
    path('api/notas/', NotasListCreateAPIView().as_view(), name='modelo-list-create'),
    path('api/notas/<int:pk>/', NotasRetrieveUpdateDestroyAPIView.as_view(), name='modelo-retrieve-update-destroy'),
    path('api/comunicados/', ComunicadoListCreateAPIView().as_view(), name='modelo-list-create'),
    path('api/comunicados/<int:pk>/', ComunicadoRetrieveUpdateDestroyAPIView.as_view(), name='modelo-retrieve-update-destroy'),
    path('api/anotaciones/', AnotacionListCreateAPIView().as_view(), name='modelo-list-create'),
    path('api/anotaciones/<int:pk>/', AnotacionRetrieveUpdateDestroyAPIView.as_view(), name='modelo-retrieve-update-destroy'),
    path('crear_clase/', crear_clase, name='crear_clase'),
    path('terminar_clase/', terminar_clase, name='terminar_clase'),
    path('incrementar_asistencia/<int:alumno_id>/',incrementar_asistencia, name='incrementar_asistencia'),


]

RegistroAppDocente/models.py
from django.db import models
from django.contrib.auth.models import User

class PeriodoSemestral(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=100)
    fecha_inicio = models.DateField()
    fecha_fin = models.DateField()

    class Meta:
        db_table = 'periodo_semestral'

    def __str__(self):
        return self.nombre

class Curso(models.Model):
    id = models.AutoField(primary_key=True)
    nombrecurso = models.CharField(max_length=100)
    aniocurso = models.IntegerField(blank=True, null=True)
    cantidadalumnos = models.IntegerField(blank=True, null=True)

    class Meta:
        db_table = 'Curso'

    def __str__(self):
        return self.nombrecurso

class Materia(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)

    class Meta:
        db_table = 'materia'

    def __str__(self):
        return self.nombre

class Clase(models.Model):
    id = models.AutoField(primary_key=True)
    fecha = models.DateField()
    periodo_semestral = models.ForeignKey(PeriodoSemestral, on_delete=models.CASCADE, null=True, blank=True)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)
    materia = models.ForeignKey(Materia, on_delete=models.CASCADE, null=True, blank=True)
    clase_iniciada = models.BooleanField(default=False)

    class Meta:
        db_table = 'clase'

def __str__(self):
    curso_nombre = self.curso.nombrecurso if self.curso else "Sin curso"
    materia_nombre = self.materia.nombre if self.materia else "Sin materia"
    return f'Clase del {self.fecha} - {curso_nombre} - {materia_nombre}'
       





class Alumno(models.Model):
    id = models.AutoField(primary_key=True)
    usera = models.OneToOneField(User, on_delete=models.CASCADE, default=None, null=True)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    foto_alumno = models.ImageField(upload_to='foto', null=True, blank=True, default='media/foto/fotodefault.png')
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE, default=None, null=True)
    asistencias = models.PositiveIntegerField(default=0)
    Reprobado = models.BooleanField(default=False)

    class Meta:
        db_table = 'alumno'

    def __str__(self):
        return str(self.usera)

    def calcular_porcentaje_asistencia(self):
        # Obtén todas las clases del curso del alumno
        total_clases_programadas = Clase.objects.filter(curso=self.curso).count()

        if total_clases_programadas > 0:
            return (self.asistencias / total_clases_programadas) * 100
        else:
            return 0.0



class Profesor(models.Model):
    id = models.AutoField(primary_key=True)
    userp = models.OneToOneField(User, on_delete=models.CASCADE, default=None, null=True)
    foto_perfil = models.ImageField(upload_to='foto', null=True, blank=True, default='media/foto/fotodefault.png')
    cursos = models.ManyToManyField(Curso)
    titulo = models.CharField(max_length=100)
    materia = models.ForeignKey(Materia, on_delete=models.CASCADE)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    cantidad_alumnos = models.IntegerField()
    correo = models.EmailField(max_length=100, unique=True)
    telefono = models.CharField(max_length=15, blank=True, null=True)
    redes_sociales = models.CharField(max_length=100, blank=True, null=True)

    class Meta:
        db_table = 'profesor'

    def __str__(self):
        return str(self.userp)

class Notas(models.Model):
    id = models.AutoField(primary_key=True)
    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE)
    parcial1 = models.DecimalField(max_digits=3, decimal_places=1, null=True)
    parcial2 = models.DecimalField(max_digits=3, decimal_places=1, null=True)
    parcial3 = models.DecimalField(max_digits=3, decimal_places=1, null=True)
    parcial4 = models.DecimalField(max_digits=3, decimal_places=1, null=True)
    examen_final = models.DecimalField(max_digits=3, decimal_places=1, null=True)

    class Meta:
        db_table = 'notas'

    def __str__(self):
        return f'Notas de {self.alumno.usera.first_name} {self.alumno.usera.last_name}'

class Comunicado(models.Model):
    URGENTE = 'U'
    GENERAL = 'G'
    
    TIPO_COMUNICADO_CHOICES = [
        (URGENTE, 'Urgente'),
        (GENERAL, 'General'),
    ]
    id = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=200)
    contenido = models.TextField()
    fecha_envio = models.DateTimeField(auto_now_add=True)
    tipo_comunicado = models.CharField(
        max_length=1,
        choices=TIPO_COMUNICADO_CHOICES,
        default=GENERAL
    )

    def __str__(self):
        return self.titulo

class Anotacion(models.Model):
    id = models.AutoField(primary_key=True)
    TIPO_ANOTACION = (
        ('bitacora', 'Bitácora'),
        ('anotacion negativa', 'Anotación Negativa'),
    )

    alumno = models.ForeignKey(Alumno, on_delete=models.CASCADE)
    tipo_anotacion = models.CharField(max_length=20, choices=TIPO_ANOTACION)
    fecha = models.DateField(auto_now=True)
    comentario = models.TextField()

    class Meta:
        db_table = 'anotacion'

    def __str__(self):
        return f'Notas de {self.alumno.usera.first_name} {self.alumno.usera.last_name}'


RegistroAppDocente/forms.py
from django import forms
from .models import Comunicado

class ComunicadoForm(forms.ModelForm):
    class Meta:
        model = Comunicado
        fields = ['titulo', 'contenido', 'tipo_comunicado']

class AsistenciaForm(forms.Form):
    asistencia = forms.BooleanField(required=False)

RegistroAppDocente/templates/PerfilProfesor.html
{% extends "base3.html" %}
{% load static %}

{% block contenedor %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-3">
            <img src="{{ profesor.foto_perfil.url }}" alt="Foto de Perfil" class="rounded-circle" width="150">
        </div>
        <div class="col-md-9">
            <h1>{{ profesor.userp.first_name }} {{ profesor.userp.last_name }}</h1>
            <p><strong>Título:</strong>  {{ profesor.titulo }}</p>
            <p><strong>Ramo que enseña:</strong> {{ profesor.materia.nombre }}</p>
            <p><strong>Fecha de Nacimiento:</strong> {{ profesor.fecha_nacimiento }}</p>
            <p><strong>Cantidad de Alumnos:</strong> {{ profesor.cantidad_alumnos }}</p>
            <p><strong>Correo Electrónico:</strong> {{ profesor.correo }}</p>
            <p><strong>Teléfono de Contacto:</strong> {{ profesor.telefono }}</p>
            <p><strong>Redes Sociales:</strong> {{ profesor.redes_sociales }}</p>
        </div>
    </div>

    <h2>Cursos que enseña</h2>
    <ul>
        {% for curso in profesor.cursos.all %}
            <li>{{ curso.nombrecurso }} ({{ curso.aniocurso }})</li>
        {% endfor %}
    </ul>
</div>
{% endblock contenedor %}

RegistroAppDocente/templates/anotaciones.html
{% extends "base3.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="{%static 'css/anotaciones.css'%}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
{% endblock css %}
{% block contenedor %}
<body>
    <div class="container mt-5 containerr">
        <h1>Página de Anotación</h1>
        <form id="Formulario">
            <div class="form-group">
                <label for="curso">Curso</label>
                <select class="form-control" id="curso" placeholder="Curso del alumno">
                    <option value="1">1-A</option>
                    <option value="2">5-B</option>
                    <option value="3">2-C</option>
                </select>
            </div>
            <div class="form-group">
                <label for="nombre">Nombre</label>
                <input type="text" class="form-control" id="nombre" placeholder="Nombre del alumno">
            </div>
            <div class="form-group">
                <label for="apellido">Apellido</label>
                <input type="text" class="form-control" id="apellido" placeholder="Apellido del alumno">
            </div>
            <div class="form-group">
                <label for="tipoAnotacion">Tipo de Anotación</label>
                <select class="form-control" id="tipoAnotacion">
                    <option value="bitacora">Bitácora</option>
                    <option value="anotacionNegativa">Anotación Negativa</option>
                </select>
            </div>
            <div class="form-group">
                <label for="comentario">Comentario</label>
                <textarea class="form-control" id="comentario" rows="5" placeholder="Escribe tu anotación aquí"></textarea>
            </div>
            <button type="button" onclick="confirmarAnotacion()">Guardar Anotación</button>
        </form>
    </div>
</body>
</html>

    {% endblock contenedor %}

RegistroAppDocente/templates/asistencia.html
{% extends "base3.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/asistencia.css' %}">
{% endblock css %}
{% block contenedor %}

<body>
    <div class="container mt-5">
        <h1>Lista de Asistencia</h1>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Foto</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Apellido Paterno</th>
                    <th scope="col">Apellido Materno</th>
                    <th scope="col">Edad</th>
                    <th scope="col">Asistencia</th>
                </tr>
            </thead>
            <tbody>
                {% for student in students %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><img src="{{ student.foto_alumno.url }}" class="rounded-circle" width="55"></td>
                    <td>{{ student.usera.first_name }}</td>
                    <td>{{ student.usera.last_name }}</td>
                    <td>{{ student.calcular_edad }}</td>
                    <td>
                        <div class="form-check">
                        <!-- Agrega un controlador de eventos onclick a los botones de radio -->
                        {% csrf_token %}
                        <input class="form-check-input" type="radio" name="asistencia_{{ student.id }}" id="presente_{{ student.id }}" value="presente" data-alumno-id="{{ student.id }}" onclick="marcarPresente(this)">
                        <label class="form-check-label" for="presente_{{ student.id }}">
                            Presente
                        </label>
                        </div>
                        <div class="form-check">
                            <!-- No necesitas un controlador de eventos para los botones de radio 'ausente' -->
                            <input class="form-check-input" type="radio" name="asistencia_{{ student.id }}" id="ausente_{{ student.id }}" value="ausente">
                            <label class="form-check-label" for="ausente_{{ student.id }}">
                                Ausente
                            </label>
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <!-- Alerta de error oculta -->
        <div id="errorAsistencia" class="alert alert-danger" style="display: none;">
            Debes marcar la asistencia de todos los estudiantes.
        </div>


        <!-- Botones -->
        <div class="row mt-3">
            <div class="col-12 col-md-6">
                <button class="btn btn-primary btn-block" type="button" id="generar-qr-button">
                    Generar Códigos QR
                </button>                
            </div>
            <div class="col-12 col-md-6">
                {% csrf_token %}
                <a class="btn btn-danger btn-block" data-clase-id="{{ clase.id }}" data-terminarclase-url="{% url 'terminar_clase' %}" data-listaasistencia-url="{% url 'LASIS' %}" onclick="terminarClase(this)">Terminar Clase</a>
            </div>
        </div>
        <div id="codigoQR" class="collapse mt-3">
            <div id="qr-codes"></div>
        </div>     
    </div>
</form>
</body>
</html>
{% endblock contenedor %}

RegistroAppDocente/templates/base2.html
<!---Con Footer--->
{% load static %}
{% block css %}

{% endblock css %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Envío de Comunicados</title>
    <!-- Enlaces a los archivos CSS de Bootstrap a través de BootstrapCDN -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{%static 'css/footer.css'%}">
</head>
<nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="{%url 'IND'%}">
        <img src="{%static 'img/LogoPNG.png'%}" alt="Logo de mi sitio web">
    </a>
    <a class="btn btn-secondary ml-2" href="{%url 'IND'%}">Volver atrás</a>
</nav>
{% block contenedor %}


{% endblock contenedor %}
<br>
    <div class="footer-dark">
        <footer>
            <div class="containerrr">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Servicios</h3>
                        <ul>
                            <li><a href="{%url 'LCUR' %}">Lista de Cursos</a></li>
                            <li><a href="{%url 'LASIS' %}">Listado de Asistencia</a></li>
                            <li><a href="{%url 'SISA' %}">Situacion de los alumnos</a></li>
                            <li><a href="{%url 'COM'%}">Generar Comunicado</a></li>
                            <li><a href="{%url 'MODN'%}">Modificar Notas</a></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Acerca de</h3>
                        <ul>
                            <li><a href="https://www.duoc.cl/sedes/puente-alto/">Duoc UC Puente Alto</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>Registra App</h3>
                        <p>Registra App WEB es una aplicación web diseñada para facilitar el seguimiento de la asistencia de los alumnos por parte de los profesores de manera eficiente y conveniente. Con esta aplicación, los profesores pueden llevar un registro preciso de la asistencia de sus estudiantes de manera rápida y sencilla.</p>
                    </div>
                    <div class="col item social"><a href="https://www.facebook.com/cittduoc.uc/?locale=es_LA"><i class="icon ion-social-facebook"></i></a><a href="https://www.instagram.com/cittduocuc/?hl=es-la"><i class="icon ion-social-instagram"></i></a></div>
                </div>
                <p class="copyright">© 2023 Registra App.</p>
            </div>
        </footer>
    </div>  

{% block js %}

{% endblock js %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
    <script src="{%static 'js/scriptsgenerales.js'%}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        // Asigna las URL a variables JavaScript
        var loginURL = "{% url 'LOG' %}";
        var dashboardURL = "{% url 'IND' %}";
        var asistenciaURL = "{% url 'ASIS' %}";
        var listaalumnosURL = "{% url 'LALU' %}";
        var listaasistenciaURL = "{% url 'LASIS' %}";
        var listacursosURL = "{% url 'LCUR' %}";
        var modificarnotasURL = "{% url 'MODN' %}";
        var notasURL = "{% url 'NON' %}";
        var situacionalumnosURL = "{% url 'SISA' %}";
        var anotacionesURL = "{% url 'ANOT' %}";
        var comunicadoURL = "{% url 'COM' %}";
    </script>
</body>
</html>

RegistroAppDocente/templates/base3.html
<!---Sin Footer-->
{% load static %}
{% block css %}

{% endblock css %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
</head>
<nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="{%url 'IND'%}">
        <img src="{%static 'img/LogoPNG.png'%}" alt="Logo de mi sitio web">
    </a>
    <a class="btn btn-secondary ml-2" href="{%url 'IND'%}">Volver atrás</a>
</nav>
{% block contenedor %}


{% endblock contenedor %}

{% block js %}

{% endblock js %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
    <script src="{%static 'js/scriptsgenerales.js'%}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        // Asigna las URL a variables JavaScript
        var loginURL = "{% url 'LOG' %}";
        var dashboardURL = "{% url 'IND' %}";
        var asistenciaURL = "{% url 'ASIS' %}";
        var listaalumnosURL = "{% url 'LALU' %}";
        var listaasistenciaURL = "{% url 'LASIS' %}";
        var listacursosURL = "{% url 'LCUR' %}";
        var modificarnotasURL = "{% url 'MODN' %}";
        var notasURL = "{% url 'NON' %}";
        var situacionalumnosURL = "{% url 'SISA' %}";
        var anotacionesURL = "{% url 'ANOT' %}";
        var comunicadoURL = "{% url 'COM' %}";
    </script>
</body>
</html>

RegistroAppDocente/templates/comunicado.html
{% extends "base3.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{%static 'css/anotaciones.css'%}">
{% endblock css %}
{% block contenedor %}
<body>
    <div class="container mt-5">
        <h1>Envío de Comunicados</h1>
        <form>
            <div class="form-group">
                <label for="tipoComunicado">Tipo de Comunicado</label>
                <select class="form-control" id="tipoComunicado">
                    <option value="general">General 📢</option>
                    <option value="urgente">Urgente 🚨</option>
                </select>
            </div>
            <div class="form-group">
                <label for="tituloComunicado">Título</label>
                <input type="text" class="form-control" id="tituloComunicado">
            </div>
            <div class="form-group">
                <label for="mensaje">Mensaje</label>
                <textarea class="form-control" id="mensaje" rows="5"></textarea>
            </div>
            <div class="d-flex justify-content-between">
                <button class="btn btn-secondary" type="reset">Limpiar</button>
                <button type="button" data-comunicados-url="{% url 'comunicado' %}" data-dashboard-url="{% url 'IND' %}" onclick="enviarComunicado(this)">Enviar Comunicado</button>
            </div>
        </form>
    </div>
{% endblock contenedor %}

 

{% block js %}
    <!-- Inclusión de Bootstrap JS a través de BootstrapCDN -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="../js/scriptsgenerales.js"></script>
{% endblock js %}

</body>
</html>

RegistroAppDocente/templates/index.html
{% extends 'base1.html' %}
{% load static %}

{% block contenedor %}
<!-- Contenido principal -->
    <div class="container-fluid mt-5">
        <div class="row">
            <!-- Menú lateral -->
            <nav class="col-md-3 col-lg-2 d-md-block bg-light sidebar">
                <div class="position-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="{%url 'LCUR'%}">
                                Lista de Cursos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{%url 'LASIS'%}">
                                Listado de Asistencia
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{%url 'SISA'%}">
                                Situación de los Alumnos
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{%url 'COM'%}">
                                Generar Comunicado
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{%url 'NON'%}">
                                Modificar Notas
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            <!-- Contenido de la página -->
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4" id="dashboard-content">
                <!-- Título del dashboard -->
                <h1 class="mt-3 dashboard-title">Bienvenido, Profesor X</h1>
                <!-- Texto de bienvenida -->
                <p>Selecciona una opción del menú lateral para comenzar.</p>
            </main>
            
        </div>
    </div>
{% endblock contenedor %}

RegistroAppDocente/templates/listadoasistencia.html
{% extends "base2.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/listadodecursos.css' %}">
{% endblock css %}
{% block contenedor %}
    <div class="container mt-5">
        <h1>Listado de Asistencia</h1>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Curso</th>
                    <th scope="col">Alumnos</th>
                    <th scope="col">% de Asistencia</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for curso in cursos %}
                <tr>
                    <td>{{ curso.nombrecurso }}</td>
                    <td>{{ curso.cantidad_alumnos }}</td>
                    <td>{{ curso.porcentaje_asistencia|floatformat:"0" }}%</td>
                    <td>
                        <form id="crearClaseForm" data-curso-id="{{ curso.id }}">
                            {% csrf_token %}
                            <a class="btn btn-primary" data-curso-id="{{ curso.id }}" data-crearclase-url="{% url 'crear_clase' %}" onclick="iniciarClase(this)">Empezar clase</a>
                        </form>
                    </td>                    
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>
{% endblock contenedor%}
{% block js %}
<script>

</script>
{% endblock js %}

RegistroAppDocente/templates/modificarnotas.html
{% extends "base3.html" %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'css/modificarnotas.css'%}">
{% endblock css %}

{% block contenedor %}
<body>
    <div class="container mt-5 notas-container">
        <h1>Modificación de Notas para {{ curso.curso_nombre }}</h1>
        <form method="post">
            {% csrf_token %}
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Nombre del Alumno</th>
                        <th scope="col">Parcial 1</th>
                        <th scope="col">Parcial 2</th>
                        <th scope="col">Parcial 3</th>
                        <th scope="col">Parcial 4</th>
                        <th scope="col">Examen Final</th>
                    </tr>
                </thead>
                <tbody>
                    {% for alumno in alumnos %}
                    {% for nota in alumno.notas_set.all %}
                        <tr>
                            <td>{{alumno.usera.first_name}} {{alumno.usera.last_name}}</td>
                            <td><input type="number" step="0.1" min="1.0" max="7.0" class="form-control" name="parcial1_{{ nota.id }}" value="{{ nota.parcial1 }}"></td>
                            <td><input type="number" step="0.1" min="1.0" max="7.0" class="form-control" name="parcial2_{{ nota.id }}" value="{{ nota.parcial2 }}"></td>
                            <td><input type="number" step="0.1" min="1.0" max="7.0" class="form-control" name="parcial3_{{ nota.id }}" value="{{ nota.parcial3 }}"></td>
                            <td><input type="number" step="0.1" min="1.0" max="7.0" class="form-control" name="parcial4_{{ nota.id }}" value="{{ nota.parcial4 }}"></td>
                            <td><input type="number" step="0.1" min="1.0" max="7.0" class="form-control" name="examen_final_{{ nota.id }}" value="{{ nota.examen_final }}"></td>
                        </tr>
                    {% endfor %}
                {% endfor %}                
                </tbody>
            </table>
            <button type="submit" class="btn btn-primary">Guardar Cambios</button>
        </form>
    </div>
</body>

{% endblock contenedor %}